# Generated by Django 5.2.7 on 2025-10-24 04:39

import django.db.models.deletion
import progress.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressStatistic',
            fields=[
                ('progressStatistic_id', models.CharField(default=progress.models.generate_short_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('topics_learned', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('tests_completed', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReminder',
            fields=[
                ('reviewReminder_id', models.CharField(default=progress.models.generate_short_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.question')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
