# Generated by Django 5.2.8 on 2025-11-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activation_expiry',
            field=models.DateTimeField(blank=True, help_text='Thời hạn nhập OTP để kích hoạt tài khoản', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
