# Generated by Django 5.2.7 on 2025-10-24 04:39

import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('Flashcard_id', models.CharField(default=learning.models.generate_short_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='flashcards/')),
                ('video', models.FileField(blank=True, null=True, upload_to='flashcard_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.CharField(default=learning.models.generate_short_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('Note_id', models.CharField(default=learning.models.generate_short_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(default=learning.models.generate_short_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Nội dung câu hỏi (dạng text)')),
                ('question_type', models.CharField(choices=[('choice', 'Trắc nghiệm'), ('text', 'Nhập câu trả lời')], default='choice', help_text='Loại câu hỏi: chọn đáp án hoặc nhập tay', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(blank=True, help_text='Câu hỏi dựa trên flashcard này', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.flashcard')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.CharField(default=learning.models.generate_short_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question')),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('user_answer_id', models.CharField(default=learning.models.generate_short_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('text_answer', models.CharField(blank=True, help_text='Câu trả lời nhập tay (nếu là câu hỏi tự luận)', max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question')),
                ('selected_answer', models.ForeignKey(blank=True, help_text='Đáp án người học chọn (nếu là trắc nghiệm)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
